apiVersion: v1
kind: Service
metadata:
  name: universal-db-mcp
  labels:
    app: universal-db-mcp
spec:
  selector:
    app: universal-db-mcp
  ports:
    - name: http
      port: 8000
      targetPort: http
    - name: sse
      port: 8001
      targetPort: sse
